#!/bin/sh

# Name of the pack
NAME="${NAME:-Creeping Dark}"
# Pack author (ideally, Curse username)
AUTHOR="${AUTHOR:-NathanRsfba}"
# Folders to include
OVERRIDES="${OVERRIDES:-mods config scripts structures resources}"
# Editor to write release notes in
EDITOR="${EDITOR:-vim}"
# Remote Git repository
REPO="${REPO:-origin}"


# github release title
title() {
    echo -n "$NAME v"
    echo "$version" | sed -e 's/a/ Alpha /' -e 's/b/ Beta /'
}

# Pack filename
filename() {
    local name="`echo $NAME | sed 's/ /-/g'`"
    name="`echo $name | tr '[:upper:]' '[:lower:]'`"
    echo "$name-`version`.zip"
}   

# git tag to create
tag() {
    echo "v`version`"
}

# Pack version
version() {
    local tag="$version"
    if echo "$tag" | grep -q a; then
        tag="`echo "$tag" | sed 's/a/-alpha./'`"
    elif echo "$tag" | grep -q b; then
        tag="`echo "$tag" | sed 's/b/-beta./'`"
    fi
    echo $tag
}

# Determine if this is a prerelease
prerelease() {
    echo "$version" | grep -q '[ab]'
}

# End of configuration

while getopts "tMemrTpP?" opt; do
    case $opt in
        t) test='echo';;
        M) manifest=1;;
        e) EDIT=1;;
        m) MKPKG=1;;
        r) RENAME=1;;
        T) TAG=1;;
        p) PUSH=1;;
        P) PUBLISH=1;;
        ?)
            echo "Usage: `basename "$0"` [-temrTpP] version"
            echo ""
            echo "-t        Test: Display what is to be done"
            echo "-M        Pass -M option to mkpkg"
            echo ""
            echo "version   Version of pack to publish"
            echo ""
            echo "The following specify what actions to perform. By default,"
            echo "all are performed:"
            echo ""
            echo "-e        Edit release notes"
            echo "-m        Make package file"
            echo "-r        Rename package to expected format"
            echo "-T        Tag repo with version"
            echo "-p        Push repo to remote"
            echo "-P        Publish to github"
            exit
            ;;
    esac
done

if [ $EDIT$MKPKG$RENAME$TAG$PUSH$PUBLISH ]; then
    # Some action was specified; do nothing
    true
else
    # Enable everything
    EDIT=1
    MKPKG=1
    RENAME=1
    TAG=1
    PUSH=1
    PUBLISH=1
fi

shift $(($OPTIND - 1))

if [ "$1" = "" ]; then
    exec $0 '-?'
fi


version="$1"
pkg="$NAME-`version`.zip"
if prerelease; then
    propts="-p"
fi

if [ $test ]; then
    echo "Pack will be created with the following attributes:"
    echo "Name:         $NAME"
    echo "Author:       $AUTHOR"
    echo "Pack version: `version`"
    echo "Title:        `title`"
    echo "Filename:     `filename`"
    echo "Git tag:      `tag`"
    echo -n "Prerelease:   "
    if prerelease; then
        echo "Yes"
    else
        echo "No"
    fi

    echo "Included directories:"
    for dir in $OVERRIDES; do
        echo "$dir"
    done

    echo "Commands that will be run:"
fi

if [ $EDIT ]; then
    echo "Running editor to edit release notes..."
    if [ ! $test ]; then
        cp release.txt release.txt.bak
    fi
    $test "$EDITOR" release.txt || exit 1
    if [ ! $test ]; then
        if ! grep -q '[^[:space:]]' release.txt; then
            echo "Empty release notes file, cancelling"
            mv release.txt.bak release.txt
            exit 
        fi
        rm release.txt.bak
    fi
fi


if [ $MKPKG ]; then
    echo "Creating pack file..."
    opts=''
    if [ $manifest ]; then
        opts='-M'
    fi
    $test tools/mkpkg.py $opts -n "$NAME" -a "$AUTHOR" "`version`" $OVERRIDES || exit 1
fi

if [ $RENAME ]; then
    echo "Renaming pack file..."
    $test mv "$pkg" "`filename`" || exit 1
fi

if [ $TAG ]; then
    echo "Tagging git repo..."
    if [ "`git tag --points-at HEAD`" = "" ]; then
        $test git tag "`tag`" || exit 1
    else
        echo "(Tag already present)"
    fi
fi

if [ $PUSH ]; then
    echo "Pushing repo..."
    $test git push "$REPO" "`git branch --show-current`" "`tag`"
fi

if [ $PUBLISH ]; then
    echo "Publishing to GitHub..."
    $test gh release create -t "`title`" -F release.txt $propts "`tag`" "`filename`" || exit 1
fi

